addons:
  apt:
    packages:
    - qt5-default
    - qt5-qmake
    - qtbase5-dev-tools
    sources:
    - ubuntu-sdk-team

os:
  - linux

language: cpp

script:
 - lrelease res/lang/en.ts
 - qmake apkstudio.pro CONFIG+=release
 - make

sudo: false
